// angular-image-search/src/app/app.component.ts
import { Component } from '@angular/core';
import { ImagesService } from './images.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private imagesService: ImagesService) { }

  title = 'Angular Image Search';
  searchTerm = '';
  loading = false;
  images = [];

  onSubmit() {
    this.loading = true;
    this.images = [];
    this.imagesService.search(this.searchTerm)
      .subscribe((result: any) => {
        this.images = result.photos;
        this.loading = false;
      });
  }
}

<h1>{{title}}</h1>
<form (ngSubmit)="onSubmit()">
  <label for="searchTerm">Search Term</label>
  <input [(ngModel)]="searchTerm" class="u-full-width" type="text" id="searchTerm" name="searchTerm">
  <button type="submit">Search</button>
</form>
<img *ngIf="loading" src="https://i.imgur.com/LVHmLnb.gif">
<section class="images">
  <img *ngFor="let image of images" src="{{image.image_url[0]}}" >
</section>

// vue-image-search/src/App.vue
<template>
  <div id="app">
    <h1>{{title}}</h1>
    <form @submit.prevent="formSubmitted()">
      <label for="searchTerm">Search Term</label>
      <input v-model="searchTerm" class="u-full-width" type="text" id="searchTerm" name="searchTerm">
      <button type="submit">Search</button>
    </form>
    <img v-if="loading" src="https://i.imgur.com/LVHmLnb.gif">
    <section class="images">
      <img v-for="image in images" :key="image.id" :src="image.image_url[0]">
    </section>
  </div>
</template>

<script>
import API from './API';

export default {
  name: 'app',
  data() {
    return {
      title: 'Vue Image Search',
      searchTerm: '',
      images: [],
      loading: false,
    };
  },
  methods: {
    formSubmitted() {
      this.loading = true;
      this.images = [];
      API.search(this.searchTerm)
        .then(images => {
          this.images = images;
          this.loading = false;
        });
    }
  },
};
</script>

<style>
body {
  width: 80%;
  margin: 2em auto 0 auto;
}

.images {
  column-count: 3;
}

img {
  width: 100%;
}
</style>
